name: trash_collection
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - cyclonedds==11.0.1
      - mujoco==3.11.0
      - numpy>=2.0,<3
      - PyYAML>=6,<7
      - pytest>=9,<10
      - trimesh==5.0.0
      - pycollada==0.9.3
      - -e .
